#*****************************************************************************
#
#Author:     Ranadip Lodh
#Purpose:    This Docker file use to install memcached container
#Date:       07/04/2020
#
#*****************************************************************************
FROM memcached:1.5.19

EXPOSE 11211