#*****************************************************************************
#
#Author:     Ranadip Lodh
#Purpose:    This Docker file use to install awx_web container
#Date:       07/04/2020
#
#*****************************************************************************
FROM ansible/awx_web:3.0.0
  
EXPOSE 8052

USER root