#*****************************************************************************
#
#Author:     Ranadip Lodh
#Purpose:    THIS YAML IS USE TO RUN PLATFORM HEALTH CHECK SCRIPT.
#Date:       30/06/2020
#
#*****************************************************************************
---
- hosts: "{{ host }}"
  remote_user: "{{ user }}"
  strategy: free
  gather_facts: no
  
  tasks:    
    - name: "Artifact results to Tower Workflows"
      set_stats:
       data:
        host_name:  "{{ host }}"
        
    - name: Test Ping
      command: ping "{{ host }}"
      register: ping_check
        
    - name: Check if sshd is running
      command: systemctl status sshd
      register: sshd_check
      ignore_errors: yes
      no_log: False
      failed_when: false   
      
          
     