#*****************************************************************************
#
#Author:     Ranadip Lodh
#Purpose:    This Docker file use to install rabbitmq container
#Date:       07/04/2020
#
#*****************************************************************************
FROM rabbitmq:3-management

EXPOSE 5672 15672